# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: npm run lint
      if: startsWith(matrix.node-version, 10) || startsWith(matrix.node-version, 12) || startsWith(matrix.node-version, 14)
      run: npm run lint

    - run: npm run type-check

    - run: npm run build

    - name: npm run test
      if: startsWith(matrix.node-version, 10) || startsWith(matrix.node-version, 12) || startsWith(matrix.node-version, 14)
      run: npm run test

  deploy:

    runs-on: ubuntu-latest

    needs: build

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build

    - name: Deploy
      uses: akhileshns/heroku-deploy@v3.4.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: pi-home
        heroku_email: gustavo.ingrassia@gmail.com
